-- migrate:up
ALTER TABLE order_details
    ADD COLUMN IF NOT EXISTS shendi_date DATE,
    ADD COLUMN IF NOT EXISTS shendi_day TEXT,
    ADD COLUMN IF NOT EXISTS shendi_time TIME,
    ADD COLUMN IF NOT EXISTS shendi_time_type TEXT,
    ADD COLUMN IF NOT EXISTS shendi_dinner_time TIME,
    ADD COLUMN IF NOT EXISTS shendi_venue_name TEXT,
    ADD COLUMN IF NOT EXISTS shendi_venue_address TEXT,
    ADD COLUMN IF NOT EXISTS shendi_arrival_time TIME,
    ADD COLUMN IF NOT EXISTS shendi_rukhsati_time TIME,
    ADD COLUMN IF NOT EXISTS shendi_sehrabandi_time TIME,
    ADD COLUMN IF NOT EXISTS shalima_date DATE,
    ADD COLUMN IF NOT EXISTS shalima_day TEXT,
    ADD COLUMN IF NOT EXISTS shalima_time TIME,
    ADD COLUMN IF NOT EXISTS shalima_time_type TEXT,
    ADD COLUMN IF NOT EXISTS shalima_dinner_time TIME,
    ADD COLUMN IF NOT EXISTS shalima_venue_name TEXT,
    ADD COLUMN IF NOT EXISTS shalima_venue_address TEXT,
    ADD COLUMN IF NOT EXISTS shalima_arrival_time TIME,
    ADD COLUMN IF NOT EXISTS shalima_rukhsati_time TIME,
    ADD COLUMN IF NOT EXISTS shalima_sehrabandi_time TIME,
    ADD COLUMN IF NOT EXISTS shalima_reception_time TIME;

-- migrate:down
ALTER TABLE order_details
    DROP COLUMN IF EXISTS shendi_date,
    DROP COLUMN IF EXISTS shendi_day,
    DROP COLUMN IF EXISTS shendi_time,
    DROP COLUMN IF EXISTS shendi_time_type,
    DROP COLUMN IF EXISTS shendi_dinner_time,
    DROP COLUMN IF EXISTS shendi_venue_name,
    DROP COLUMN IF EXISTS shendi_venue_address,
    DROP COLUMN IF EXISTS shendi_arrival_time,
    DROP COLUMN IF EXISTS shendi_rukhsati_time,
    DROP COLUMN IF EXISTS shendi_sehrabandi_time,
    DROP COLUMN IF EXISTS shalima_date,
    DROP COLUMN IF EXISTS shalima_day,
    DROP COLUMN IF EXISTS shalima_time,
    DROP COLUMN IF EXISTS shalima_time_type,
    DROP COLUMN IF EXISTS shalima_dinner_time,
    DROP COLUMN IF EXISTS shalima_venue_name,
    DROP COLUMN IF EXISTS shalima_venue_address,
    DROP COLUMN IF EXISTS shalima_arrival_time,
    DROP COLUMN IF EXISTS shalima_rukhsati_time,
    DROP COLUMN IF EXISTS shalima_sehrabandi_time,
    DROP COLUMN IF EXISTS shalima_reception_time;
