-- migrate:up
CREATE TABLE IF NOT EXISTS order_details (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    side TEXT NOT NULL DEFAULT 'bride',
    bride_name TEXT,
    groom_name TEXT,
    bride_father_name TEXT,
    groom_father_name TEXT,
    mehndi_date DATE,
    mehndi_time_type TEXT,
    mehndi_time TIME,
    mehndi_dinner_time TIME,
    baraat_date DATE,
    baraat_time_type TEXT,
    baraat_time TIME,
    baraat_dinner_time TIME,
    baraat_arrival_time TIME,
    rukhsati_time TIME,
    nikkah_date DATE,
    nikkah_time_type TEXT,
    nikkah_time TIME,
    nikkah_dinner_time TIME,
    walima_date DATE,
    walima_time_type TEXT,
    walima_time TIME,
    walima_dinner_time TIME,
    reception_time TIME,
    dinner_time TIME,
    venue_name TEXT NOT NULL,
    venue_address TEXT NOT NULL,
    rsvp_name TEXT NOT NULL,
    rsvp_phone TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE order_details
    ADD COLUMN IF NOT EXISTS side TEXT DEFAULT 'bride' NOT NULL,
    ADD COLUMN IF NOT EXISTS bride_name TEXT,
    ADD COLUMN IF NOT EXISTS groom_name TEXT,
    ADD COLUMN IF NOT EXISTS bride_father_name TEXT,
    ADD COLUMN IF NOT EXISTS groom_father_name TEXT,
    ADD COLUMN IF NOT EXISTS mehndi_date DATE,
    ADD COLUMN IF NOT EXISTS mehndi_time_type TEXT,
    ADD COLUMN IF NOT EXISTS mehndi_time TIME,
    ADD COLUMN IF NOT EXISTS mehndi_dinner_time TIME,
    ADD COLUMN IF NOT EXISTS baraat_date DATE,
    ADD COLUMN IF NOT EXISTS baraat_time_type TEXT,
    ADD COLUMN IF NOT EXISTS baraat_time TIME,
    ADD COLUMN IF NOT EXISTS baraat_dinner_time TIME,
    ADD COLUMN IF NOT EXISTS baraat_arrival_time TIME,
    ADD COLUMN IF NOT EXISTS rukhsati_time TIME,
    ADD COLUMN IF NOT EXISTS nikkah_date DATE,
    ADD COLUMN IF NOT EXISTS nikkah_time_type TEXT,
    ADD COLUMN IF NOT EXISTS nikkah_time TIME,
    ADD COLUMN IF NOT EXISTS nikkah_dinner_time TIME,
    ADD COLUMN IF NOT EXISTS walima_date DATE,
    ADD COLUMN IF NOT EXISTS walima_time_type TEXT,
    ADD COLUMN IF NOT EXISTS walima_time TIME,
    ADD COLUMN IF NOT EXISTS walima_dinner_time TIME,
    ADD COLUMN IF NOT EXISTS reception_time TIME,
    ADD COLUMN IF NOT EXISTS dinner_time TIME,
    ADD COLUMN IF NOT EXISTS venue_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS venue_address TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS rsvp_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS rsvp_phone TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS notes TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE order_details
    ALTER COLUMN bride_name DROP NOT NULL,
    ALTER COLUMN groom_name DROP NOT NULL,
    ALTER COLUMN bride_father_name DROP NOT NULL,
    ALTER COLUMN groom_father_name DROP NOT NULL,
    ALTER COLUMN mehndi_date DROP NOT NULL,
    ALTER COLUMN mehndi_time_type DROP NOT NULL,
    ALTER COLUMN mehndi_time DROP NOT NULL,
    ALTER COLUMN mehndi_dinner_time DROP NOT NULL,
    ALTER COLUMN baraat_date DROP NOT NULL,
    ALTER COLUMN baraat_time_type DROP NOT NULL,
    ALTER COLUMN baraat_time DROP NOT NULL,
    ALTER COLUMN baraat_dinner_time DROP NOT NULL,
    ALTER COLUMN baraat_arrival_time DROP NOT NULL,
    ALTER COLUMN rukhsati_time DROP NOT NULL,
    ALTER COLUMN nikkah_date DROP NOT NULL,
    ALTER COLUMN nikkah_time_type DROP NOT NULL,
    ALTER COLUMN nikkah_time DROP NOT NULL,
    ALTER COLUMN nikkah_dinner_time DROP NOT NULL,
    ALTER COLUMN walima_date DROP NOT NULL,
    ALTER COLUMN walima_time_type DROP NOT NULL,
    ALTER COLUMN walima_time DROP NOT NULL,
    ALTER COLUMN walima_dinner_time DROP NOT NULL,
    ALTER COLUMN reception_time DROP NOT NULL,
    ALTER COLUMN dinner_time DROP NOT NULL,
    ALTER COLUMN notes DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_order_details_order_id ON order_details(order_id);


-- migrate:down
DROP TABLE IF EXISTS order_details;
