// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package customerreader

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        int64
	Name      string
	Email     *string
	Phone     *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
