// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package customerreader

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, email, phone, address, city, postal_code, created_at, updated_at
FROM customers
WHERE id = $1
`

type GetCustomerByIDRow struct {
	ID         int64
	Name       string
	Email      *string
	Phone      *string
	Address    *string
	City       *string
	PostalCode *string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetCustomerByID(ctx context.Context, id int64) (GetCustomerByIDRow, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i GetCustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.PostalCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
