// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package orderreader

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_id, card_id, quantity, total_price, status, currency, created_at, updated_at
FROM orders
WHERE id = $1
`

type GetOrderByIDRow struct {
	ID         int64
	CustomerID *int64
	CardID     *int64
	Quantity   int64
	TotalPrice int64
	Status     *string
	Currency   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CardID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByCustomerID = `-- name: GetOrdersByCustomerID :many
SELECT id, customer_id, card_id, quantity, total_price, status, currency, created_at, updated_at
FROM orders
WHERE customer_id = $1
ORDER BY created_at DESC
`

type GetOrdersByCustomerIDRow struct {
	ID         int64
	CustomerID *int64
	CardID     *int64
	Quantity   int64
	TotalPrice int64
	Status     *string
	Currency   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) GetOrdersByCustomerID(ctx context.Context, customerID *int64) ([]GetOrdersByCustomerIDRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByCustomerIDRow
	for rows.Next() {
		var i GetOrdersByCustomerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.CardID,
			&i.Quantity,
			&i.TotalPrice,
			&i.Status,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
