// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cardwriter

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CardImage struct {
	ID        int64
	CardID    int64
	Image     string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
}
