// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package cardwriter

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID          int64
	Name        string
	Description *string
	Price       int64
	Image       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
