// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package cardwriter

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (name, description, price_foil_pkr, price_nofoil_pkr, price_foil_nok, price_nofoil_nok, insert_price_pkr, insert_price_nok, min_order, included_inserts, image, category)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, name, description, price_foil_pkr, price_nofoil_pkr, price_foil_nok, price_nofoil_nok, insert_price_pkr, insert_price_nok, min_order, included_inserts, image, category, created_at, updated_at
`

type CreateCardParams struct {
	Name            string
	Description     *string
	PriceFoilPkr    int64
	PriceNofoilPkr  int64
	PriceFoilNok    int64
	PriceNofoilNok  int64
	InsertPricePkr  int64
	InsertPriceNok  int64
	MinOrder        int32
	IncludedInserts int32
	Image           string
	Category        string
}

type CreateCardRow struct {
	ID              int64
	Name            string
	Description     *string
	PriceFoilPkr    int64
	PriceNofoilPkr  int64
	PriceFoilNok    int64
	PriceNofoilNok  int64
	InsertPricePkr  int64
	InsertPriceNok  int64
	MinOrder        int32
	IncludedInserts int32
	Image           string
	Category        string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (CreateCardRow, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.Name,
		arg.Description,
		arg.PriceFoilPkr,
		arg.PriceNofoilPkr,
		arg.PriceFoilNok,
		arg.PriceNofoilNok,
		arg.InsertPricePkr,
		arg.InsertPriceNok,
		arg.MinOrder,
		arg.IncludedInserts,
		arg.Image,
		arg.Category,
	)
	var i CreateCardRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceFoilPkr,
		&i.PriceNofoilPkr,
		&i.PriceFoilNok,
		&i.PriceNofoilNok,
		&i.InsertPricePkr,
		&i.InsertPriceNok,
		&i.MinOrder,
		&i.IncludedInserts,
		&i.Image,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCardImage = `-- name: CreateCardImage :one
INSERT INTO card_images (card_id, image, sort_order)
VALUES ($1, $2, $3)
RETURNING id, card_id, image, sort_order, created_at
`

type CreateCardImageParams struct {
	CardID    int64
	Image     string
	SortOrder int32
}

func (q *Queries) CreateCardImage(ctx context.Context, arg CreateCardImageParams) (CardImage, error) {
	row := q.db.QueryRow(ctx, createCardImage, arg.CardID, arg.Image, arg.SortOrder)
	var i CardImage
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Image,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards
WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const deleteCardImagesByCardID = `-- name: DeleteCardImagesByCardID :exec
DELETE FROM card_images
WHERE card_id = $1
`

func (q *Queries) DeleteCardImagesByCardID(ctx context.Context, cardID int64) error {
	_, err := q.db.Exec(ctx, deleteCardImagesByCardID, cardID)
	return err
}

const updateCard = `-- name: UpdateCard :exec
UPDATE cards
SET name = $2,
    description = $3,
    price_foil_pkr = $4,
    price_nofoil_pkr = $5,
    price_foil_nok = $6,
    price_nofoil_nok = $7,
    insert_price_pkr = $8,
    insert_price_nok = $9,
    min_order = $10,
    included_inserts = $11,
    image = $12,
    category = $13,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateCardParams struct {
	ID              int64
	Name            string
	Description     *string
	PriceFoilPkr    int64
	PriceNofoilPkr  int64
	PriceFoilNok    int64
	PriceNofoilNok  int64
	InsertPricePkr  int64
	InsertPriceNok  int64
	MinOrder        int32
	IncludedInserts int32
	Image           string
	Category        string
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) error {
	_, err := q.db.Exec(ctx, updateCard,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceFoilPkr,
		arg.PriceNofoilPkr,
		arg.PriceFoilNok,
		arg.PriceNofoilNok,
		arg.InsertPricePkr,
		arg.InsertPriceNok,
		arg.MinOrder,
		arg.IncludedInserts,
		arg.Image,
		arg.Category,
	)
	return err
}
