// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package cardwriter

import (
	"context"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (name, description, price, image)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, price, image, created_at, updated_at
`

type CreateCardParams struct {
	Name        string
	Description *string
	Price       int64
	Image       string
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Image,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards
WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const updateCard = `-- name: UpdateCard :exec
UPDATE cards
SET name = $2, description = $3, price = $4, image = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateCardParams struct {
	ID          int64
	Name        string
	Description *string
	Price       int64
	Image       string
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) error {
	_, err := q.db.Exec(ctx, updateCard,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Image,
	)
	return err
}
