// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package productreader

import (
	"context"
)

const getProduct = `-- name: GetProduct :one
SELECT id, card_id, name, category, price, image_url, description, dimensions, is_active
FROM products
WHERE id = $1
`

type GetProductRow struct {
	ID          int32
	CardID      *int64
	Name        string
	Category    string
	Price       int32
	ImageUrl    *string
	Description *string
	Dimensions  *string
	IsActive    *bool
}

func (q *Queries) GetProduct(ctx context.Context, id int32) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.ImageUrl,
		&i.Description,
		&i.Dimensions,
		&i.IsActive,
	)
	return i, err
}

const getProductImages = `-- name: GetProductImages :many
SELECT image_url
FROM product_images
WHERE product_id = $1
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) GetProductImages(ctx context.Context, productID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_url string
		if err := rows.Scan(&image_url); err != nil {
			return nil, err
		}
		items = append(items, image_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, card_id, name, category, price, image_url, description, dimensions, is_active
FROM products
ORDER BY id DESC
`

type ListProductsRow struct {
	ID          int32
	CardID      *int64
	Name        string
	Category    string
	Price       int32
	ImageUrl    *string
	Description *string
	Dimensions  *string
	IsActive    *bool
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Name,
			&i.Category,
			&i.Price,
			&i.ImageUrl,
			&i.Description,
			&i.Dimensions,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
