// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package accessoryreader

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Accessory struct {
	ID          int64
	Name        string
	Category    string
	Description *string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AccessoryImage struct {
	ID          int64
	AccessoryID int64
	ImageUrl    string
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
}
