// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package accessoryreader

import (
	"context"
)

const getAccessoryImagesByAccessoryID = `-- name: GetAccessoryImagesByAccessoryID :many
SELECT id, accessory_id, image_url, sort_order, created_at
FROM accessory_images
WHERE accessory_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) GetAccessoryImagesByAccessoryID(ctx context.Context, accessoryID int64) ([]AccessoryImage, error) {
	rows, err := q.db.Query(ctx, getAccessoryImagesByAccessoryID, accessoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessoryImage
	for rows.Next() {
		var i AccessoryImage
		if err := rows.Scan(
			&i.ID,
			&i.AccessoryID,
			&i.ImageUrl,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAccessories = `-- name: ListActiveAccessories :many
SELECT id, name, category, description, is_active, created_at, updated_at
FROM accessories
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveAccessories(ctx context.Context) ([]Accessory, error) {
	rows, err := q.db.Query(ctx, listActiveAccessories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Accessory
	for rows.Next() {
		var i Accessory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
