// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package productwriter

import (
	"context"
)

const addProductImage = `-- name: AddProductImage :exec
INSERT INTO product_images (product_id, image_url, sort_order)
VALUES ($1, $2, $3)
`

type AddProductImageParams struct {
	ProductID int32
	ImageUrl  string
	SortOrder *int32
}

func (q *Queries) AddProductImage(ctx context.Context, arg AddProductImageParams) error {
	_, err := q.db.Exec(ctx, addProductImage, arg.ProductID, arg.ImageUrl, arg.SortOrder)
	return err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (card_id, name, category, price, image_url, description, dimensions, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, card_id, name, category, price, image_url, description, dimensions, is_active
`

type CreateProductParams struct {
	CardID      *int64
	Name        string
	Category    string
	Price       int32
	ImageUrl    *string
	Description *string
	Dimensions  *string
	IsActive    *bool
}

type CreateProductRow struct {
	ID          int32
	CardID      *int64
	Name        string
	Category    string
	Price       int32
	ImageUrl    *string
	Description *string
	Dimensions  *string
	IsActive    *bool
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CardID,
		arg.Name,
		arg.Category,
		arg.Price,
		arg.ImageUrl,
		arg.Description,
		arg.Dimensions,
		arg.IsActive,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Name,
		&i.Category,
		&i.Price,
		&i.ImageUrl,
		&i.Description,
		&i.Dimensions,
		&i.IsActive,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET card_id = $2,
    name = $3,
    category = $4,
    price = $5,
    image_url = $6,
    description = $7,
    dimensions = $8,
    is_active = $9,
    updated_at = NOW()
WHERE id = $1
`

type UpdateProductParams struct {
	ID          int32
	CardID      *int64
	Name        string
	Category    string
	Price       int32
	ImageUrl    *string
	Description *string
	Dimensions  *string
	IsActive    *bool
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.CardID,
		arg.Name,
		arg.Category,
		arg.Price,
		arg.ImageUrl,
		arg.Description,
		arg.Dimensions,
		arg.IsActive,
	)
	return err
}
