// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package orderwriter

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id, card_id, quantity, total_price, status, currency)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, customer_id, card_id, quantity, total_price, status, currency, created_at, updated_at
`

type CreateOrderParams struct {
	CustomerID *int64
	CardID     *int64
	Quantity   int64
	TotalPrice int64
	Status     *string
	Currency   string
}

type CreateOrderRow struct {
	ID         int64
	CustomerID *int64
	CardID     *int64
	Quantity   int64
	TotalPrice int64
	Status     *string
	Currency   string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.CustomerID,
		arg.CardID,
		arg.Quantity,
		arg.TotalPrice,
		arg.Status,
		arg.Currency,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CardID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderDetail = `-- name: CreateOrderDetail :one
INSERT INTO order_details (
    order_id,
    side,
    top_label,
    couple_name,
    event_date,
    bid_box_details,
    bride_name,
    groom_name,
    bride_father_name,
    groom_father_name,
    mehndi_date,
    mehndi_day,
    mehndi_time_type,
    mehndi_time,
    mehndi_dinner_time,
    mehndi_venue_name,
    mehndi_venue_address,
    baraat_date,
    baraat_day,
    baraat_time_type,
    baraat_time,
    baraat_dinner_time,
    baraat_arrival_time,
    rukhsati_time,
    baraat_venue_name,
    baraat_venue_address,
    nikkah_date,
    nikkah_day,
    nikkah_time_type,
    nikkah_time,
    nikkah_dinner_time,
    nikkah_venue_name,
    nikkah_venue_address,
    walima_date,
    walima_day,
    walima_time_type,
    walima_time,
    walima_dinner_time,
    reception_time,
    walima_venue_name,
    walima_venue_address,
    rsvp_name,
    rsvp_phone,
    notes
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NULLIF($5, ''),
    $6,
    $7,
    $8,
    $9,
    $10,
    NULLIF($11, '')::date,
    $12,
    $13,
    NULLIF($14, '')::time,
    NULLIF($15, '')::time,
    $16,
    $17,
    NULLIF($18, '')::date,
    $19,
    $20,
    NULLIF($21, '')::time,
    NULLIF($22, '')::time,
    NULLIF($23, '')::time,
    NULLIF($24, '')::time,
    $25,
    $26,
    NULLIF($27, '')::date,
    $28,
    $29,
    NULLIF($30, '')::time,
    NULLIF($31, '')::time,
    $32,
    $33,
    NULLIF($34, '')::date,
    $35,
    $36,
    NULLIF($37, '')::time,
    NULLIF($38, '')::time,
    NULLIF($39, '')::time,
    $40,
    $41,
    $42,
    $43,
    $44
)
RETURNING
    id,
    order_id,
    side,
    COALESCE(top_label, '') AS top_label,
    COALESCE(couple_name, '') AS couple_name,
    COALESCE(event_date, '') AS event_date,
    COALESCE(bid_box_details, '') AS bid_box_details,
    bride_name,
    groom_name,
    bride_father_name,
    groom_father_name,
    COALESCE(mehndi_date::text, '')::text AS mehndi_date,
    mehndi_day,
    mehndi_time_type,
    COALESCE(mehndi_time::text, '')::text AS mehndi_time,
    COALESCE(mehndi_dinner_time::text, '')::text AS mehndi_dinner_time,
    COALESCE(mehndi_venue_name, '') AS mehndi_venue_name,
    COALESCE(mehndi_venue_address, '') AS mehndi_venue_address,
    COALESCE(baraat_date::text, '')::text AS baraat_date,
    baraat_day,
    baraat_time_type,
    COALESCE(baraat_time::text, '')::text AS baraat_time,
    COALESCE(baraat_dinner_time::text, '')::text AS baraat_dinner_time,
    COALESCE(baraat_arrival_time::text, '')::text AS baraat_arrival_time,
    COALESCE(rukhsati_time::text, '')::text AS rukhsati_time,
    COALESCE(baraat_venue_name, '') AS baraat_venue_name,
    COALESCE(baraat_venue_address, '') AS baraat_venue_address,
    COALESCE(nikkah_date::text, '')::text AS nikkah_date,
    nikkah_day,
    nikkah_time_type,
    COALESCE(nikkah_time::text, '')::text AS nikkah_time,
    COALESCE(nikkah_dinner_time::text, '')::text AS nikkah_dinner_time,
    COALESCE(nikkah_venue_name, '') AS nikkah_venue_name,
    COALESCE(nikkah_venue_address, '') AS nikkah_venue_address,
    COALESCE(walima_date::text, '')::text AS walima_date,
    walima_day,
    walima_time_type,
    COALESCE(walima_time::text, '')::text AS walima_time,
    COALESCE(walima_dinner_time::text, '')::text AS walima_dinner_time,
    COALESCE(reception_time::text, '')::text AS reception_time,
    COALESCE(walima_venue_name, '') AS walima_venue_name,
    COALESCE(walima_venue_address, '') AS walima_venue_address,
    rsvp_name,
    rsvp_phone,
    notes,
    created_at
`

type CreateOrderDetailParams struct {
	OrderID            int64
	Side               string
	TopLabel           *string
	CoupleName         *string
	BidBoxEventDate    interface{}
	BidBoxDetails      *string
	BrideName          *string
	GroomName          *string
	BrideFatherName    *string
	GroomFatherName    *string
	MehndiDate         interface{}
	MehndiDay          *string
	MehndiTimeType     *string
	MehndiTime         interface{}
	MehndiDinnerTime   interface{}
	MehndiVenueName    *string
	MehndiVenueAddress *string
	BaraatDate         interface{}
	BaraatDay          *string
	BaraatTimeType     *string
	BaraatTime         interface{}
	BaraatDinnerTime   interface{}
	BaraatArrivalTime  interface{}
	RukhsatiTime       interface{}
	BaraatVenueName    *string
	BaraatVenueAddress *string
	NikkahDate         interface{}
	NikkahDay          *string
	NikkahTimeType     *string
	NikkahTime         interface{}
	NikkahDinnerTime   interface{}
	NikkahVenueName    *string
	NikkahVenueAddress *string
	WalimaDate         interface{}
	WalimaDay          *string
	WalimaTimeType     *string
	WalimaTime         interface{}
	WalimaDinnerTime   interface{}
	ReceptionTime      interface{}
	WalimaVenueName    *string
	WalimaVenueAddress *string
	RsvpName           string
	RsvpPhone          string
	Notes              *string
}

type CreateOrderDetailRow struct {
	ID                 int64
	OrderID            int64
	Side               string
	TopLabel           string
	CoupleName         string
	EventDate          string
	BidBoxDetails      string
	BrideName          *string
	GroomName          *string
	BrideFatherName    *string
	GroomFatherName    *string
	MehndiDate         string
	MehndiDay          *string
	MehndiTimeType     *string
	MehndiTime         string
	MehndiDinnerTime   string
	MehndiVenueName    string
	MehndiVenueAddress string
	BaraatDate         string
	BaraatDay          *string
	BaraatTimeType     *string
	BaraatTime         string
	BaraatDinnerTime   string
	BaraatArrivalTime  string
	RukhsatiTime       string
	BaraatVenueName    string
	BaraatVenueAddress string
	NikkahDate         string
	NikkahDay          *string
	NikkahTimeType     *string
	NikkahTime         string
	NikkahDinnerTime   string
	NikkahVenueName    string
	NikkahVenueAddress string
	WalimaDate         string
	WalimaDay          *string
	WalimaTimeType     *string
	WalimaTime         string
	WalimaDinnerTime   string
	ReceptionTime      string
	WalimaVenueName    string
	WalimaVenueAddress string
	RsvpName           string
	RsvpPhone          string
	Notes              *string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateOrderDetail(ctx context.Context, arg CreateOrderDetailParams) (CreateOrderDetailRow, error) {
	row := q.db.QueryRow(ctx, createOrderDetail,
		arg.OrderID,
		arg.Side,
		arg.TopLabel,
		arg.CoupleName,
		arg.BidBoxEventDate,
		arg.BidBoxDetails,
		arg.BrideName,
		arg.GroomName,
		arg.BrideFatherName,
		arg.GroomFatherName,
		arg.MehndiDate,
		arg.MehndiDay,
		arg.MehndiTimeType,
		arg.MehndiTime,
		arg.MehndiDinnerTime,
		arg.MehndiVenueName,
		arg.MehndiVenueAddress,
		arg.BaraatDate,
		arg.BaraatDay,
		arg.BaraatTimeType,
		arg.BaraatTime,
		arg.BaraatDinnerTime,
		arg.BaraatArrivalTime,
		arg.RukhsatiTime,
		arg.BaraatVenueName,
		arg.BaraatVenueAddress,
		arg.NikkahDate,
		arg.NikkahDay,
		arg.NikkahTimeType,
		arg.NikkahTime,
		arg.NikkahDinnerTime,
		arg.NikkahVenueName,
		arg.NikkahVenueAddress,
		arg.WalimaDate,
		arg.WalimaDay,
		arg.WalimaTimeType,
		arg.WalimaTime,
		arg.WalimaDinnerTime,
		arg.ReceptionTime,
		arg.WalimaVenueName,
		arg.WalimaVenueAddress,
		arg.RsvpName,
		arg.RsvpPhone,
		arg.Notes,
	)
	var i CreateOrderDetailRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Side,
		&i.TopLabel,
		&i.CoupleName,
		&i.EventDate,
		&i.BidBoxDetails,
		&i.BrideName,
		&i.GroomName,
		&i.BrideFatherName,
		&i.GroomFatherName,
		&i.MehndiDate,
		&i.MehndiDay,
		&i.MehndiTimeType,
		&i.MehndiTime,
		&i.MehndiDinnerTime,
		&i.MehndiVenueName,
		&i.MehndiVenueAddress,
		&i.BaraatDate,
		&i.BaraatDay,
		&i.BaraatTimeType,
		&i.BaraatTime,
		&i.BaraatDinnerTime,
		&i.BaraatArrivalTime,
		&i.RukhsatiTime,
		&i.BaraatVenueName,
		&i.BaraatVenueAddress,
		&i.NikkahDate,
		&i.NikkahDay,
		&i.NikkahTimeType,
		&i.NikkahTime,
		&i.NikkahDinnerTime,
		&i.NikkahVenueName,
		&i.NikkahVenueAddress,
		&i.WalimaDate,
		&i.WalimaDay,
		&i.WalimaTimeType,
		&i.WalimaTime,
		&i.WalimaDinnerTime,
		&i.ReceptionTime,
		&i.WalimaVenueName,
		&i.WalimaVenueAddress,
		&i.RsvpName,
		&i.RsvpPhone,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int64
	Status *string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
