-- name: CreateOrder :one
INSERT INTO orders (customer_id, card_id, quantity, total_price, status, currency)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, customer_id, card_id, quantity, total_price, status, currency, created_at, updated_at;

-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1;

-- name: CreateOrderDetail :one
INSERT INTO order_details (
    order_id,
    side,
    bride_name,
    groom_name,
    bride_father_name,
    groom_father_name,
    mehndi_date,
    mehndi_day,
    mehndi_time_type,
    mehndi_time,
    mehndi_dinner_time,
    mehndi_venue_name,
    mehndi_venue_address,
    baraat_date,
    baraat_day,
    baraat_time_type,
    baraat_time,
    baraat_dinner_time,
    baraat_arrival_time,
    rukhsati_time,
    baraat_venue_name,
    baraat_venue_address,
    nikkah_date,
    nikkah_day,
    nikkah_time_type,
    nikkah_time,
    nikkah_dinner_time,
    nikkah_venue_name,
    nikkah_venue_address,
    walima_date,
    walima_day,
    walima_time_type,
    walima_time,
    walima_dinner_time,
    reception_time,
    walima_venue_name,
    walima_venue_address,
    rsvp_name,
    rsvp_phone,
    notes
)
VALUES (
    sqlc.arg(order_id),
    sqlc.arg(side),
    sqlc.arg(bride_name),
    sqlc.arg(groom_name),
    sqlc.arg(bride_father_name),
    sqlc.arg(groom_father_name),
    NULLIF(sqlc.arg(mehndi_date), '')::date,
    sqlc.arg(mehndi_day),
    sqlc.arg(mehndi_time_type),
    NULLIF(sqlc.arg(mehndi_time), '')::time,
    NULLIF(sqlc.arg(mehndi_dinner_time), '')::time,
    sqlc.arg(mehndi_venue_name),
    sqlc.arg(mehndi_venue_address),
    NULLIF(sqlc.arg(baraat_date), '')::date,
    sqlc.arg(baraat_day),
    sqlc.arg(baraat_time_type),
    NULLIF(sqlc.arg(baraat_time), '')::time,
    NULLIF(sqlc.arg(baraat_dinner_time), '')::time,
    NULLIF(sqlc.arg(baraat_arrival_time), '')::time,
    NULLIF(sqlc.arg(rukhsati_time), '')::time,
    sqlc.arg(baraat_venue_name),
    sqlc.arg(baraat_venue_address),
    NULLIF(sqlc.arg(nikkah_date), '')::date,
    sqlc.arg(nikkah_day),
    sqlc.arg(nikkah_time_type),
    NULLIF(sqlc.arg(nikkah_time), '')::time,
    NULLIF(sqlc.arg(nikkah_dinner_time), '')::time,
    sqlc.arg(nikkah_venue_name),
    sqlc.arg(nikkah_venue_address),
    NULLIF(sqlc.arg(walima_date), '')::date,
    sqlc.arg(walima_day),
    sqlc.arg(walima_time_type),
    NULLIF(sqlc.arg(walima_time), '')::time,
    NULLIF(sqlc.arg(walima_dinner_time), '')::time,
    NULLIF(sqlc.arg(reception_time), '')::time,
    sqlc.arg(walima_venue_name),
    sqlc.arg(walima_venue_address),
    sqlc.arg(rsvp_name),
    sqlc.arg(rsvp_phone),
    sqlc.arg(notes)
)
RETURNING
    id,
    order_id,
    side,
    bride_name,
    groom_name,
    bride_father_name,
    groom_father_name,
    COALESCE(mehndi_date::text, '')::text AS mehndi_date,
    mehndi_day,
    mehndi_time_type,
    COALESCE(mehndi_time::text, '')::text AS mehndi_time,
    COALESCE(mehndi_dinner_time::text, '')::text AS mehndi_dinner_time,
    COALESCE(mehndi_venue_name, '') AS mehndi_venue_name,
    COALESCE(mehndi_venue_address, '') AS mehndi_venue_address,
    COALESCE(baraat_date::text, '')::text AS baraat_date,
    baraat_day,
    baraat_time_type,
    COALESCE(baraat_time::text, '')::text AS baraat_time,
    COALESCE(baraat_dinner_time::text, '')::text AS baraat_dinner_time,
    COALESCE(baraat_arrival_time::text, '')::text AS baraat_arrival_time,
    COALESCE(rukhsati_time::text, '')::text AS rukhsati_time,
    COALESCE(baraat_venue_name, '') AS baraat_venue_name,
    COALESCE(baraat_venue_address, '') AS baraat_venue_address,
    COALESCE(nikkah_date::text, '')::text AS nikkah_date,
    nikkah_day,
    nikkah_time_type,
    COALESCE(nikkah_time::text, '')::text AS nikkah_time,
    COALESCE(nikkah_dinner_time::text, '')::text AS nikkah_dinner_time,
    COALESCE(nikkah_venue_name, '') AS nikkah_venue_name,
    COALESCE(nikkah_venue_address, '') AS nikkah_venue_address,
    COALESCE(walima_date::text, '')::text AS walima_date,
    walima_day,
    walima_time_type,
    COALESCE(walima_time::text, '')::text AS walima_time,
    COALESCE(walima_dinner_time::text, '')::text AS walima_dinner_time,
    COALESCE(reception_time::text, '')::text AS reception_time,
    COALESCE(walima_venue_name, '') AS walima_venue_name,
    COALESCE(walima_venue_address, '') AS walima_venue_address,
    rsvp_name,
    rsvp_phone,
    notes,
    created_at;
