-- name: CreateOrder :one
INSERT INTO orders (customer_id, card_id, quantity, total_price, status, currency)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, customer_id, card_id, quantity, total_price, status, currency, public_token::text AS public_token, created_at, updated_at;

-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1;

-- name: CreateOrderPayment :one
INSERT INTO order_payments (
    order_id,
    payment_method,
    payment_status,
    expected_amount
)
VALUES ($1, $2, $3, $4)
RETURNING
    id,
    order_id,
    payment_method,
    payment_status,
    expected_amount,
    submitted_amount,
    sender_name,
    transaction_reference,
    proof_file_path,
    customer_note,
    submitted_at,
    verified_at,
    rejected_at,
    admin_note,
    created_at,
    updated_at;

-- name: SubmitOrderPaymentProof :one
UPDATE order_payments
SET
    payment_status = $2,
    submitted_amount = $3,
    sender_name = $4,
    transaction_reference = $5,
    proof_file_path = $6,
    customer_note = $7,
    submitted_at = CURRENT_TIMESTAMP,
    verified_at = NULL,
    rejected_at = NULL,
    admin_note = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE order_id = $1
RETURNING
    id,
    order_id,
    payment_method,
    payment_status,
    expected_amount,
    submitted_amount,
    sender_name,
    transaction_reference,
    proof_file_path,
    customer_note,
    submitted_at,
    verified_at,
    rejected_at,
    admin_note,
    created_at,
    updated_at;

-- name: VerifyOrderPayment :one
UPDATE order_payments
SET
    payment_status = 'payment_verified',
    admin_note = $2,
    verified_at = CURRENT_TIMESTAMP,
    rejected_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE order_id = $1
RETURNING
    id,
    order_id,
    payment_method,
    payment_status,
    expected_amount,
    submitted_amount,
    sender_name,
    transaction_reference,
    proof_file_path,
    customer_note,
    submitted_at,
    verified_at,
    rejected_at,
    admin_note,
    created_at,
    updated_at;

-- name: RejectOrderPayment :one
UPDATE order_payments
SET
    payment_status = 'payment_rejected',
    admin_note = $2,
    rejected_at = CURRENT_TIMESTAMP,
    verified_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE order_id = $1
RETURNING
    id,
    order_id,
    payment_method,
    payment_status,
    expected_amount,
    submitted_amount,
    sender_name,
    transaction_reference,
    proof_file_path,
    customer_note,
    submitted_at,
    verified_at,
    rejected_at,
    admin_note,
    created_at,
    updated_at;

-- name: SubmitOrderFinalPaymentProof :one
UPDATE orders
SET
    final_payment_status = $2,
    final_payment_proof_url = $3,
    final_payment_sender_name = $4,
    final_payment_submitted_at = CURRENT_TIMESTAMP,
    final_payment_verified_at = NULL,
    final_payment_rejected_at = NULL,
    final_payment_admin_note = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING
    id,
    status,
    final_payment_status,
    final_payment_proof_url,
    final_payment_sender_name,
    final_payment_submitted_at,
    final_payment_verified_at,
    final_payment_rejected_at,
    final_payment_admin_note,
    updated_at;

-- name: VerifyOrderFinalPayment :one
UPDATE orders
SET
    final_payment_status = 'payment_verified',
    final_payment_admin_note = $2,
    final_payment_verified_at = CURRENT_TIMESTAMP,
    final_payment_rejected_at = NULL,
    status = 'shipped',
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING
    id,
    status,
    final_payment_status,
    final_payment_proof_url,
    final_payment_sender_name,
    final_payment_submitted_at,
    final_payment_verified_at,
    final_payment_rejected_at,
    final_payment_admin_note,
    updated_at;

-- name: RejectOrderFinalPayment :one
UPDATE orders
SET
    final_payment_status = 'payment_rejected',
    final_payment_admin_note = $2,
    final_payment_rejected_at = CURRENT_TIMESTAMP,
    final_payment_verified_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING
    id,
    status,
    final_payment_status,
    final_payment_proof_url,
    final_payment_sender_name,
    final_payment_submitted_at,
    final_payment_verified_at,
    final_payment_rejected_at,
    final_payment_admin_note,
    updated_at;

-- name: CreateOrderDetail :one
INSERT INTO order_details (
    order_id,
    side,
    extra_inserts_per_card,
    top_label,
    couple_name,
    event_date,
    bid_box_details,
    bride_name,
    groom_name,
    bride_father_name,
    groom_father_name,
    mehndi_date,
    mehndi_day,
    mehndi_time_type,
    mehndi_time,
    mehndi_dinner_time,
    mehndi_venue_name,
    mehndi_venue_address,
    baraat_date,
    baraat_day,
    baraat_time_type,
    baraat_time,
    baraat_dinner_time,
    baraat_arrival_time,
    rukhsati_time,
    baraat_sehrabandi_time,
    baraat_venue_name,
    baraat_venue_address,
    nikkah_date,
    nikkah_day,
    nikkah_time_type,
    nikkah_time,
    nikkah_dinner_time,
    nikkah_venue_name,
    nikkah_venue_address,
    walima_date,
    walima_day,
    walima_time_type,
    walima_time,
    walima_dinner_time,
    reception_time,
    walima_venue_name,
    walima_venue_address,
    shendi_date,
    shendi_day,
    shendi_time,
    shendi_time_type,
    shendi_dinner_time,
    shendi_venue_name,
    shendi_venue_address,
    shendi_arrival_time,
    shendi_rukhsati_time,
    shendi_sehrabandi_time,
    shalima_date,
    shalima_day,
    shalima_time,
    shalima_time_type,
    shalima_dinner_time,
    shalima_venue_name,
    shalima_venue_address,
    shalima_arrival_time,
    shalima_rukhsati_time,
    shalima_sehrabandi_time,
    shalima_reception_time,
    rsvp_name,
    rsvp_phone,
    notes
)
VALUES (
    sqlc.arg(order_id),
    sqlc.arg(side),
    sqlc.arg(extra_inserts_per_card),
    sqlc.arg(top_label),
    sqlc.arg(couple_name),
    NULLIF(sqlc.arg(bid_box_event_date), ''),
    sqlc.arg(bid_box_details),
    sqlc.arg(bride_name),
    sqlc.arg(groom_name),
    sqlc.arg(bride_father_name),
    sqlc.arg(groom_father_name),
    NULLIF(sqlc.arg(mehndi_date), '')::date,
    sqlc.arg(mehndi_day),
    sqlc.arg(mehndi_time_type),
    NULLIF(sqlc.arg(mehndi_time), '')::time,
    NULLIF(sqlc.arg(mehndi_dinner_time), '')::time,
    sqlc.arg(mehndi_venue_name),
    sqlc.arg(mehndi_venue_address),
    NULLIF(sqlc.arg(baraat_date), '')::date,
    sqlc.arg(baraat_day),
    sqlc.arg(baraat_time_type),
    NULLIF(sqlc.arg(baraat_time), '')::time,
    NULLIF(sqlc.arg(baraat_dinner_time), '')::time,
    NULLIF(sqlc.arg(baraat_arrival_time), '')::time,
    NULLIF(sqlc.arg(rukhsati_time), '')::time,
    NULLIF(sqlc.arg(baraat_sehrabandi_time), '')::time,
    sqlc.arg(baraat_venue_name),
    sqlc.arg(baraat_venue_address),
    NULLIF(sqlc.arg(nikkah_date), '')::date,
    sqlc.arg(nikkah_day),
    sqlc.arg(nikkah_time_type),
    NULLIF(sqlc.arg(nikkah_time), '')::time,
    NULLIF(sqlc.arg(nikkah_dinner_time), '')::time,
    sqlc.arg(nikkah_venue_name),
    sqlc.arg(nikkah_venue_address),
    NULLIF(sqlc.arg(walima_date), '')::date,
    sqlc.arg(walima_day),
    sqlc.arg(walima_time_type),
    NULLIF(sqlc.arg(walima_time), '')::time,
    NULLIF(sqlc.arg(walima_dinner_time), '')::time,
    NULLIF(sqlc.arg(reception_time), '')::time,
    sqlc.arg(walima_venue_name),
    sqlc.arg(walima_venue_address),
    NULLIF(sqlc.arg(shendi_date), '')::date,
    sqlc.arg(shendi_day),
    NULLIF(sqlc.arg(shendi_time), '')::time,
    sqlc.arg(shendi_time_type),
    NULLIF(sqlc.arg(shendi_dinner_time), '')::time,
    sqlc.arg(shendi_venue_name),
    sqlc.arg(shendi_venue_address),
    NULLIF(sqlc.arg(shendi_arrival_time), '')::time,
    NULLIF(sqlc.arg(shendi_rukhsati_time), '')::time,
    NULLIF(sqlc.arg(shendi_sehrabandi_time), '')::time,
    NULLIF(sqlc.arg(shalima_date), '')::date,
    sqlc.arg(shalima_day),
    NULLIF(sqlc.arg(shalima_time), '')::time,
    sqlc.arg(shalima_time_type),
    NULLIF(sqlc.arg(shalima_dinner_time), '')::time,
    sqlc.arg(shalima_venue_name),
    sqlc.arg(shalima_venue_address),
    NULLIF(sqlc.arg(shalima_arrival_time), '')::time,
    NULLIF(sqlc.arg(shalima_rukhsati_time), '')::time,
    NULLIF(sqlc.arg(shalima_sehrabandi_time), '')::time,
    NULLIF(sqlc.arg(shalima_reception_time), '')::time,
    sqlc.arg(rsvp_name),
    sqlc.arg(rsvp_phone),
    sqlc.arg(notes)
)
RETURNING
    id,
    order_id,
    side,
    extra_inserts_per_card,
    COALESCE(top_label, '') AS top_label,
    COALESCE(couple_name, '') AS couple_name,
    COALESCE(event_date, '') AS event_date,
    COALESCE(bid_box_details, '') AS bid_box_details,
    bride_name,
    groom_name,
    bride_father_name,
    groom_father_name,
    COALESCE(mehndi_date::text, '')::text AS mehndi_date,
    mehndi_day,
    mehndi_time_type,
    COALESCE(mehndi_time::text, '')::text AS mehndi_time,
    COALESCE(mehndi_dinner_time::text, '')::text AS mehndi_dinner_time,
    COALESCE(mehndi_venue_name, '') AS mehndi_venue_name,
    COALESCE(mehndi_venue_address, '') AS mehndi_venue_address,
    COALESCE(baraat_date::text, '')::text AS baraat_date,
    baraat_day,
    baraat_time_type,
    COALESCE(baraat_time::text, '')::text AS baraat_time,
    COALESCE(baraat_dinner_time::text, '')::text AS baraat_dinner_time,
    COALESCE(baraat_arrival_time::text, '')::text AS baraat_arrival_time,
    COALESCE(rukhsati_time::text, '')::text AS rukhsati_time,
    COALESCE(baraat_sehrabandi_time::text, '')::text AS baraat_sehrabandi_time,
    COALESCE(baraat_venue_name, '') AS baraat_venue_name,
    COALESCE(baraat_venue_address, '') AS baraat_venue_address,
    COALESCE(nikkah_date::text, '')::text AS nikkah_date,
    nikkah_day,
    nikkah_time_type,
    COALESCE(nikkah_time::text, '')::text AS nikkah_time,
    COALESCE(nikkah_dinner_time::text, '')::text AS nikkah_dinner_time,
    COALESCE(nikkah_venue_name, '') AS nikkah_venue_name,
    COALESCE(nikkah_venue_address, '') AS nikkah_venue_address,
    COALESCE(walima_date::text, '')::text AS walima_date,
    walima_day,
    walima_time_type,
    COALESCE(walima_time::text, '')::text AS walima_time,
    COALESCE(walima_dinner_time::text, '')::text AS walima_dinner_time,
    COALESCE(reception_time::text, '')::text AS reception_time,
    COALESCE(walima_venue_name, '') AS walima_venue_name,
    COALESCE(walima_venue_address, '') AS walima_venue_address,
    COALESCE(shendi_date::text, '')::text AS shendi_date,
    shendi_day,
    COALESCE(shendi_time::text, '')::text AS shendi_time,
    shendi_time_type,
    COALESCE(shendi_dinner_time::text, '')::text AS shendi_dinner_time,
    COALESCE(shendi_venue_name, '') AS shendi_venue_name,
    COALESCE(shendi_venue_address, '') AS shendi_venue_address,
    COALESCE(shendi_arrival_time::text, '')::text AS shendi_arrival_time,
    COALESCE(shendi_rukhsati_time::text, '')::text AS shendi_rukhsati_time,
    COALESCE(shendi_sehrabandi_time::text, '')::text AS shendi_sehrabandi_time,
    COALESCE(shalima_date::text, '')::text AS shalima_date,
    shalima_day,
    COALESCE(shalima_time::text, '')::text AS shalima_time,
    shalima_time_type,
    COALESCE(shalima_dinner_time::text, '')::text AS shalima_dinner_time,
    COALESCE(shalima_venue_name, '') AS shalima_venue_name,
    COALESCE(shalima_venue_address, '') AS shalima_venue_address,
    COALESCE(shalima_arrival_time::text, '')::text AS shalima_arrival_time,
    COALESCE(shalima_rukhsati_time::text, '')::text AS shalima_rukhsati_time,
    COALESCE(shalima_sehrabandi_time::text, '')::text AS shalima_sehrabandi_time,
    COALESCE(shalima_reception_time::text, '')::text AS shalima_reception_time,
    rsvp_name,
    rsvp_phone,
    notes,
    created_at;
