// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package orderwriter

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id, card_id, quantity, total_price, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, card_id, quantity, total_price, status, created_at, updated_at
`

type CreateOrderParams struct {
	CustomerID *int64
	CardID     *int64
	Quantity   int64
	TotalPrice int64
	Status     *string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.CustomerID,
		arg.CardID,
		arg.Quantity,
		arg.TotalPrice,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CardID,
		&i.Quantity,
		&i.TotalPrice,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     int64
	Status *string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
